/*-------------------------------------------------------------------------
 *
 * pg_cluster_meta_nodes_d.h
 *    Macro definitions for pg_cluster_meta_nodes
 *
 * Portions Copyright (c) 1996-2018, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_CLUSTER_META_NODES_D_H
#define PG_CLUSTER_META_NODES_D_H

#define ClusterMetaNodesRelationId 12350

#define Anum_pg_cluster_meta_nodes_server_id 1
#define Anum_pg_cluster_meta_nodes_cluster_id 2
#define Anum_pg_cluster_meta_nodes_is_master 3
#define Anum_pg_cluster_meta_nodes_port 4
#define Anum_pg_cluster_meta_nodes_ip 5
#define Anum_pg_cluster_meta_nodes_user_name 6
#define Anum_pg_cluster_meta_nodes_passwd 7

#define Natts_pg_cluster_meta_nodes 7


#endif							/* PG_CLUSTER_META_NODES_D_H */
