/*-------------------------------------------------------------------------
 *
 * pg_computing_node_stat_d.h
 *    Macro definitions for pg_computing_node_stat
 *
 * Portions Copyright (c) 1996-2018, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_COMPUTING_NODE_STAT_D_H
#define PG_COMPUTING_NODE_STAT_D_H

#define ComputingNodeStatRelationId 12347

#define Anum_pg_computing_node_stat_comp_node_id 1
#define Anum_pg_computing_node_stat_num_queries 2
#define Anum_pg_computing_node_stat_num_1shard_queries 3
#define Anum_pg_computing_node_stat_num_slow_queries 4
#define Anum_pg_computing_node_stat_num_rejected_queries 5
#define Anum_pg_computing_node_stat_num_illegal_queries 6
#define Anum_pg_computing_node_stat_num_ro_queries 7
#define Anum_pg_computing_node_stat_num_sent_queries 8
#define Anum_pg_computing_node_stat_num_recv_res 9
#define Anum_pg_computing_node_stat_num_txns 10
#define Anum_pg_computing_node_stat_num_1shard_txns 11
#define Anum_pg_computing_node_stat_num_ro_txns 12
#define Anum_pg_computing_node_stat_num_rb_txns 13
#define Anum_pg_computing_node_stat_num_rb_txns_deadlock 14
#define Anum_pg_computing_node_stat_accumulated_since 15

#define Natts_pg_computing_node_stat 15


#endif							/* PG_COMPUTING_NODE_STAT_D_H */
