/*-------------------------------------------------------------------------
 *
 * pg_cluster_meta_d.h
 *    Macro definitions for pg_cluster_meta
 *
 * Portions Copyright (c) 1996-2018, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_CLUSTER_META_D_H
#define PG_CLUSTER_META_D_H

#define ClusterMetaRelationId 12349

#define Anum_pg_cluster_meta_comp_node_id 1
#define Anum_pg_cluster_meta_cluster_id 2
#define Anum_pg_cluster_meta_cluster_master_id 3
#define Anum_pg_cluster_meta_cluster_name 4
#define Anum_pg_cluster_meta_comp_node_name 5

#define Natts_pg_cluster_meta 5


#endif							/* PG_CLUSTER_META_D_H */
