/*-------------------------------------------------------------------------
 *
 * pg_ddl_log_progress_d.h
 *    Macro definitions for pg_ddl_log_progress
 *
 * Portions Copyright (c) 1996-2018, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_DDL_LOG_PROGRESS_D_H
#define PG_DDL_LOG_PROGRESS_D_H

#define DDLLogProgressRelationId 12348

#define Anum_pg_ddl_log_progress_dbid 1
#define Anum_pg_ddl_log_progress_ddl_op_id 2
#define Anum_pg_ddl_log_progress_max_op_id_done_local 3

#define Natts_pg_ddl_log_progress 3


#endif							/* PG_DDL_LOG_PROGRESS_D_H */
