/*-------------------------------------------------------------------------
 *
 * pg_shard_d.h
 *    Macro definitions for pg_shard
 *
 * Portions Copyright (c) 1996-2018, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_SHARD_D_H
#define PG_SHARD_D_H

#define ShardRelationId 12346

#define Anum_pg_shard_name 1
#define Anum_pg_shard_id 2
#define Anum_pg_shard_master_node_id 3
#define Anum_pg_shard_num_nodes 4
#define Anum_pg_shard_space_volumn 5
#define Anum_pg_shard_num_tablets 6
#define Anum_pg_shard_db_cluster_id 7
#define Anum_pg_shard_when_created 8

#define Natts_pg_shard 8


#endif							/* PG_SHARD_D_H */
