/*-------------------------------------------------------------------------
 *
 * pg_shard_node_d.h
 *    Macro definitions for pg_shard_node
 *
 * Portions Copyright (c) 1996-2018, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_SHARD_NODE_D_H
#define PG_SHARD_NODE_D_H

#define ShardNodeRelationId 12345

#define Anum_pg_shard_node_id 1
#define Anum_pg_shard_node_port 2
#define Anum_pg_shard_node_shard_id 3
#define Anum_pg_shard_node_svr_node_id 4
#define Anum_pg_shard_node_ro_weight 5
#define Anum_pg_shard_node_ip 6
#define Anum_pg_shard_node_user_name 7
#define Anum_pg_shard_node_passwd 8
#define Anum_pg_shard_node_when_created 9

#define Natts_pg_shard_node 9


#endif							/* PG_SHARD_NODE_D_H */
